spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:1997/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:1998/
          predicates:
            - Path= /products/**


